apiVersion: apps/v1
kind: Deployment
metadata:
  name: anagram
spec:
  selector:
    matchLabels:
      app: anagram
  replicas: 3
  template:
    metadata:
      labels:
        app: anagram
    spec:
      containers:
        - name: anagram-pod
          image: hirenapatel1109/parsely-image:latest
          ports:
            - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: anagram-service
spec:
  selector:
    app: anagram
  ports:
    - protocol: TCP
      targetPort: 5000
      port: 80
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: anagram-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: anagram-service
    servicePort: 80
